-- Task internal/external comments, customer portal comment visibility, project material descriptions,
-- and reserved customer email outbox for future SMTP worker.

ALTER TABLE kpm_task_comments
  ADD COLUMN IF NOT EXISTS comment_type TEXT NOT NULL DEFAULT 'internal';

UPDATE kpm_task_comments
SET comment_type='internal'
WHERE comment_type IS NULL OR comment_type='';

ALTER TABLE kpm_stage_materials
  ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE kpm_project_materials
  ADD COLUMN IF NOT EXISTS description TEXT;

CREATE TABLE IF NOT EXISTS kpm_customer_email_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_email TEXT NOT NULL,
  recipient_name TEXT,
  subject TEXT NOT NULL,
  content TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'system',
  related_project_id BIGINT REFERENCES kpm_projects(id) ON DELETE SET NULL,
  related_task_id BIGINT REFERENCES kpm_tasks(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  last_error TEXT,
  sent_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator TEXT,
  updator TEXT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  del_flag SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_kpm_task_comments_type
  ON kpm_task_comments (task_id, comment_type, created_at)
  WHERE del_flag=0;

CREATE INDEX IF NOT EXISTS idx_kpm_customer_email_outbox_status
  ON kpm_customer_email_outbox (status, created_at DESC)
  WHERE del_flag=0;
